# Generated by Django 5.2.17 on 2026-09-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateCardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_code', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('machine', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pay_type', models.CharField(choices=[('operator', 'Operator'), ('helper', 'Helper'), ('finishing', 'Finishing')], default='operator', max_length=10)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='piecerate.style')),
            ],
            options={
                'ordering': ['op_code'],
                'constraints': [models.UniqueConstraint(fields=('style', 'op_code'), name='unique_style_opcode')],
            },
        ),
    ]
