# Generated by Django 5.2.17 on 2026-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
    ]
