# Generated by Django 5.2.17 on 2026-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0002_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
