# Generated by Django 5.2.17 on 2026-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0003_operation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='machine',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
