# Generated by Django 5.2.17 on 2026-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0004_operation_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='pay_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('helper', 'Helper'), ('finishing', 'Finishing')], default='operator', max_length=10),
        ),
    ]
