# Generated by Django 5.2.17 on 2026-09-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0005_operation_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='piecerate.style'),
        ),
        migrations.AddField(
            model_name='style',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
