# Generated by Django 5.2.17 on 2026-09-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0006_style_is_template_style_month_style_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='style',
            name='month',
        ),
        migrations.RemoveField(
            model_name='style',
            name='template',
        ),
        migrations.RemoveField(
            model_name='style',
            name='year',
        ),
    ]
