# Generated by Django 5.2.17 on 2026-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0007_remove_style_is_template_remove_style_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
