# Generated by Django 5.2.17 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0008_style_month_style_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
