# Generated by Django 5.2.17 on 2026-09-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0009_style_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The style this one was duplicated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='piecerate.style'),
        ),
    ]
