# Generated by Django 5.2.17 on 2026-09-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0010_style_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='source',
        ),
    ]
