# Generated by Django 5.2.17 on 2026-09-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_remove_employee_profession_tax_and_more'),
        ('piecerate', '0013_ratecardoperation_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecardoperation',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0, help_text="Total pieces planned for this operation this month — the target every operator's daily entries for it should sum to."),
        ),
        migrations.CreateModel(
            name='PieceRateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_rate_entries', to='attendance.employee')),
                ('rate_card_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='piecerate.ratecardoperation')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('rate_card_operation', 'employee', 'date'), name='unique_entry_per_operator_per_day')],
            },
        ),
    ]
