# Generated by Django 5.2.17 on 2026-09-17 06:34

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_remove_employee_profession_tax_and_more'),
        ('piecerate', '0015_production_head_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=43, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piece_rate_link', to='attendance.employee')),
            ],
        ),
    ]
