# Generated by Django 5.2.17 on 2026-09-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0016_operatorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='style_images/'),
        ),
        migrations.AddField(
            model_name='style',
            name='tamil_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
