# Generated by Django 5.2.17 on 2026-09-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0017_style_image_style_tamil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
