# Generated by Django 5.2.17 on 2026-09-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0018_style_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='tamil_name',
        ),
    ]
