# Generated by Django 5.2.17 on 2026-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0019_remove_style_tamil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecerateentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
