# Generated by Django 5.2.17 on 2026-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0020_piecerateentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecerateentry',
            name='entered_by',
            field=models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor')], default='supervisor', max_length=10),
        ),
    ]
