# Generated by Django 5.2.17 on 2026-09-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0021_piecerateentry_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecerateentry',
            name='was_operator_entered',
            field=models.BooleanField(default=False),
        ),
    ]
