# Generated by Django 5.2.17 on 2026-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0022_piecerateentry_was_operator_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecerateentry',
            name='operator_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
