# Generated by Django 5.2.17 on 2026-10-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0023_piecerateentry_operator_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecardoperation',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
