# Generated by Django 5.2.17 on 2026-10-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0024_ratecardoperation_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='piecerateentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ratecardoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ratecardoperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]


def _clear_backfilled_timestamps(apps, schema_editor):
    """AddField fills an auto_now/auto_now_add column on every existing row
    with the migration's own run time — blank those instead, so a row
    created before tracking started never claims to be from today."""
    for op in Migration.operations:
        if isinstance(op, migrations.AddField):
            apps.get_model('piecerate', op.model_name).objects.update(**{op.name: None})


Migration.operations.append(migrations.RunPython(_clear_backfilled_timestamps, migrations.RunPython.noop))
