# Generated by Django 5.2.17 on 2026-10-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecerate', '0025_operation_created_at_operation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorlink',
            name='show_rate_to_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OperatorSummaryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
