# Generated by Django 5.2.17 on 2026-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, help_text='Broad category from the attendance export, e.g. Staff/Helper/Worker.', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
