# Generated by Django 5.2.17 on 2026-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_category_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
