# Generated by Django 5.2.17 on 2026-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employee_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day_type', models.CharField(choices=[('H', 'Holiday'), ('PH', 'Paid Holiday'), ('CO', 'Comp Off')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
