# Generated by Django 5.2.17 on 2026-08-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_monthlock'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlock',
            name='unique_month_lock',
        ),
        migrations.AddField(
            model_name='monthlock',
            name='view',
            field=models.CharField(choices=[('all', 'All'), ('issues', 'Missed Punch'), ('ot', 'OT View')], default='all', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='monthlock',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'view'), name='unique_month_view_lock'),
        ),
    ]
