# Generated by Django 5.2.17 on 2026-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_monthlock_unique_month_lock_monthlock_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
