# Generated by Django 5.2.17 on 2026-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_employee_account_name_employee_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ot_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime pay rate for this employee, per hour.', max_digits=8),
        ),
    ]
