# Generated by Django 5.2.17 on 2026-08-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employee_ot_rate_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if still active.', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_periods', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__name', 'start_date'],
            },
        ),
    ]
