# Generated by Django 5.2.17 on 2026-08-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_backfill_employment_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='esi_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('adjust_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hold', models.BooleanField(default=False, help_text="Withhold this month's pay (still computed, not paid).")),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_adjustments', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__code'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_employee_salary_month')],
            },
        ),
    ]
