# Generated by Django 5.2.17 on 2026-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employee_basic_salary_employee_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esi_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tds_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
