# Generated by Django 5.2.17 on 2026-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_employee_esi_enabled_employee_pf_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('purpose', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
            },
        ),
    ]
