# Generated by Django 5.2.17 on 2026-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_salary_viewer_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('in', 'Cash In'), ('out', 'Cash Out')], max_length=3)),
                ('purpose', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'created_at', 'id'],
            },
        ),
    ]
