# Generated by Django 5.2.17 on 2026-08-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_cashregisterentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('full_ot_days', models.IntegerField(default=0)),
                ('el_credited', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('el_encashed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('el_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comp_off_hours_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comp_off_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_manual', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ledger_entries', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__name', 'year', 'month'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_leave_ledger_month')],
            },
        ),
    ]
