# Generated by Django 5.2.17 on 2026-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveledgerentry',
            name='el_taken',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
