# Generated by Django 5.2.17 on 2026-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_leaveledgerentry_el_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PH', 'Paid Holiday'), ('CO', 'Comp Off'), ('PL', 'Personal Leave'), ('WO', 'Week Off'), ('H', 'Holiday'), ('HD', 'Half Day'), ('EL', 'Earned Leave'), ('PM', 'Permission')], max_length=5),
        ),
    ]
