# Generated by Django 5.2.17 on 2026-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveledgerentry',
            name='full_ot_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
