# Generated by Django 5.2.17 on 2026-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_leaveledgerentry_full_ot_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialday',
            name='downgraded_employees',
            field=models.ManyToManyField(blank=True, related_name='downgraded_special_days', to='attendance.employee'),
        ),
    ]
