# Generated by Django 5.2.17 on 2026-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_specialday_downgraded_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
