# Generated by Django 5.2.17 on 2026-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_attendancerecord_manually_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyClosureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('full_day_hours', models.DecimalField(decimal_places=2, help_text='Expected full-day hours for this date (e.g. 5.5 for a half-day close), replacing the usual 8.5h.', max_digits=4)),
                ('note', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
