# Generated by Django 5.2.17 on 2026-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_earlyclosureday_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='manually_edited_fields',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
