# Generated by Django 5.2.17 on 2026-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_alter_monthlock_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('Operator', 'Operator')], help_text='Set to "Operator" for piece-rate Operators (see Subcategory for the Company/OT variants) — leave blank for everyone else, including Company Workers/Helpers/Staff (those are set via Subcategory instead) and Contractors/Fixed Payments (set via Department instead).', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Helper', 'Helper'), ('Staff', 'Staff'), ('OT', 'OT')], help_text='"Company"/"Helper"/"Staff" put a non-Operator on that Salary tab. Alongside category="Operator": blank is a plain Operator, "Company" also does salaried Company Worker days some of the month (paid on both tabs, with the Company Worker pay auto-subtracted from Operators pay), "OT" only does OT work and is hidden from the regular Attendance dashboard.', max_length=100),
        ),
    ]
