# Generated by Django 5.2.17 on 2026-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_employee_edit_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlock',
            name='view',
            field=models.CharField(choices=[('all', 'All'), ('issues', 'Missed Punch'), ('ot', 'OT View'), ('salary_company', 'Salary — Company Workers'), ('salary_helper', 'Salary — Helpers'), ('salary_staff', 'Salary — Staff'), ('salary_contractors', 'Salary — Contractors'), ('salary_operators', 'Salary — Operators'), ('salary_ironing_bartrack', 'Salary — Ironing & Bartrack'), ('salary_fixed_payments', 'Salary — Fixed Payments')], default='all', max_length=24),
        ),
    ]
