# Generated by Django 5.2.17 on 2026-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_monthlock_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Helper', 'Helper'), ('Staff', 'Staff'), ('OT', 'OT'), ('Bartrack', 'Bartrack')], help_text='"Company"/"Helper"/"Staff" put a non-Operator on that Salary tab. Alongside category="Operator": blank is a plain Operator, "Company" also does salaried Company Worker days some of the month (paid on both tabs, with the Company Worker pay auto-subtracted from Operators pay), "OT" only does OT work and is hidden from the regular Attendance dashboard, "Bartrack" also does some Ironing & Bartrack piece-rate work (listed on that tab too, with its amount zeroed out there so it isn\'t double-counted — the real payment stays on Operators).', max_length=100),
        ),
    ]
