# Generated by Django 5.2.17 on 2026-09-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_alter_employee_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('Operator', 'Operator'), ('Bartrack', 'Bartrack')], help_text='Extra flag on top of Department="Operator" (which alone decides Operators-tab membership) — "Bartrack" additionally puts them on the Ironing & Bartrack tab too, paid once via Operators. Leave blank for everyone else, including Company Workers/Helpers/Staff (set via Subcategory instead) and Contractors/Fixed Payments (set via Department instead).', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Helper', 'Helper'), ('Staff', 'Staff'), ('OT', 'OT')], help_text='"Company"/"Helper"/"Staff" put a non-Operator on that Salary tab. "OT" (meaningful only for an employee in the "Operator" department) means they only do OT work and is hidden from the regular Attendance dashboard.', max_length=100),
        ),
    ]
