# Generated by Django 5.2.17 on 2026-09-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_alter_employee_category_alter_employee_subcategory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salaryadjustment',
            name='unique_employee_salary_month',
        ),
        migrations.AddField(
            model_name='salaryadjustment',
            name='tab',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='salaryadjustment',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month', 'tab'), name='unique_employee_salary_month_tab'),
        ),
    ]
