# Generated by Django 5.2.17 on 2026-09-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_remove_salaryadjustment_unique_employee_salary_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('tab', models.CharField(max_length=30)),
                ('row_data', models.JSONField()),
                ('employee_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_snapshots', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__code'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month', 'tab'), name='unique_payroll_snapshot')],
            },
        ),
    ]
