# Generated by Django 5.2.17 on 2026-09-12 13:06

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_payrollsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsnapshot',
            name='employee_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='payrollsnapshot',
            name='row_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
