# Generated by Django 5.2.17 on 2026-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_alter_payrollsnapshot_employee_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], default='bank_transfer', max_length=20),
        ),
    ]
