# Generated by Django 5.2.17 on 2026-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_employee_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profession_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
