# Generated by Django 5.2.17 on 2026-09-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_employee_profession_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profession_tax',
        ),
        migrations.AddField(
            model_name='salaryadjustment',
            name='profession_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
