# Generated by Django 5.2.17 on 2026-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_operator_link_revoker_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permission_allowance_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text="Permission Hours allowed per month for this employee before the excess is deducted from their OT (see attendance/views.py's _permission_label). 2 hours for everyone by default — override per employee here.", max_digits=5),
        ),
    ]
