# Generated by Django 5.2.17 on 2026-09-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_employee_permission_allowance_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_adjustments', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__code'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_employee_ot_adjustment_month')],
            },
        ),
    ]
