# Generated by Django 5.2.17 on 2026-09-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_otadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permission_allowance_hours',
        ),
    ]
