# Generated by Django 5.2.17 on 2026-09-21 17:34

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_remove_employee_permission_allowance_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('view', models.CharField(max_length=24)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_snapshots', to='attendance.employee')),
            ],
            options={
                'ordering': ['employee__code'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month', 'view'), name='unique_employee_detail_snapshot')],
            },
        ),
    ]
