# Generated by Django 5.2.17 on 2026-10-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_auditlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pt_remittance_source',
            field=models.CharField(blank=True, choices=[('company', 'Company Workers'), ('staff', 'Staff'), ('ironing_bartrack', 'Ironing & Bartrack')], max_length=20),
        ),
    ]
