# Generated by Django 5.2.17 on 2026-10-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_employee_pt_remittance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pt_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
